// <auto-generated />
namespace Congreso_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class webinar3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(webinar3));
        
        string IMigrationMetadata.Id
        {
            get { return "202007282347540_webinar3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
