// <auto-generated />
namespace Congreso_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class singleWebinarUserAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(singleWebinarUserAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202007231559556_singleWebinarUserAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
